rules = {
    "dim red bag": ["2 bright gold bag", "5 striped fuchsia bag"],
    "dotted purple bag": ["5 bright olive bag", "3 faded maroon bag"],
    "plaid chartreuse bag": [
        "1 vibrant olive bag",
        "5 bright black bag",
        "1 clear tomato bag",
    ],
    "wavy orange bag": ["4 dark lavender bag", "4 posh white bag"],
    "light lavender bag": ["4 drab olive bag", "5 dark magenta bag"],
    "pale black bag": [
        "5 dotted beige bag",
        "5 clear chartreuse bag",
        "4 pale lime bag",
    ],
    "wavy crimson bag": ["5 dull tomato bag"],
    "muted aqua bag": ["1 dotted aqua bag", "5 posh plum bag", "1 bright blue bag"],
    "striped green bag": ["3 light silver bag", "2 plaid purple bag"],
    "plaid cyan bag": ["3 pale maroon bag", "2 bright yellow bag"],
    "dull maroon bag": [
        "2 wavy black bag",
        "2 plaid tomato bag",
        "2 dim silver bag",
        "3 plaid salmon bag",
    ],
    "bright gold bag": [
        "4 wavy olive bag",
        "3 muted gray bag",
        "4 dark indigo bag",
        "5 dark chartreuse bag",
    ],
    "drab blue bag": ["1 light green bag"],
    "muted brown bag": ["4 dark red bag", "5 dull aqua bag", "4 drab blue bag"],
    "bright olive bag": ["5 dim salmon bag", "4 dotted beige bag", "2 pale bronze bag"],
    "mirrored red bag": [
        "3 mirrored chartreuse bag",
        "3 muted gold bag",
        "5 bright beige bag",
        "4 dim green bag",
    ],
    "pale gray bag": ["4 vibrant tomato bag"],
    "striped purple bag": ["5 dotted gray bag"],
    "light brown bag": ["1 shiny silver bag", "3 plaid olive bag", "1 clear tan bag"],
    "dim tan bag": ["1 posh black bag", "3 faded maroon bag", "5 bright gray bag"],
    "faded fuchsia bag": [
        "5 posh fuchsia bag",
        "3 drab salmon bag",
        "1 posh orange bag",
    ],
    "dim gray bag": [
        "4 bright crimson bag",
        "5 dotted salmon bag",
        "2 plaid indigo bag",
    ],
    "bright tan bag": ["2 posh lime bag"],
    "faded olive bag": [
        "5 light fuchsia bag",
        "1 shiny orange bag",
        "4 posh lavender bag",
    ],
    "vibrant indigo bag": [
        "3 vibrant turquoise bag",
        "4 faded magenta bag",
        "4 pale red bag",
        "4 mirrored turquoise bag",
    ],
    "clear salmon bag": ["3 pale maroon bag", "5 drab green bag", "1 light green bag"],
    "clear maroon bag": [
        "2 pale black bag",
        "5 dark coral bag",
        "3 dark purple bag",
        "2 vibrant blue bag",
    ],
    "clear olive bag": ["2 muted brown bag"],
    "drab bronze bag": ["3 wavy brown bag", "4 posh lime bag", "1 mirrored beige bag"],
    "dull red bag": [
        "3 dark cyan bag",
        "5 bright indigo bag",
        "4 clear brown bag",
        "5 plaid violet bag",
    ],
    "vibrant green bag": [
        "3 clear brown bag",
        "5 plaid yellow bag",
        "4 vibrant crimson bag",
    ],
    "dark bronze bag": ["5 dark silver bag"],
    "mirrored orange bag": [
        "2 shiny crimson bag",
        "3 clear tomato bag",
        "1 muted crimson bag",
    ],
    "pale yellow bag": ["1 bright olive bag"],
    "dotted teal bag": ["1 plaid olive bag", "2 drab white bag"],
    "dull tan bag": ["2 faded aqua bag", "3 muted green bag"],
    "clear crimson bag": ["3 dark purple bag"],
    "light violet bag": ["3 pale beige bag", "2 mirrored silver bag"],
    "muted green bag": [
        "2 wavy brown bag",
        "3 dull gray bag",
        "4 drab tan bag",
        "3 plaid teal bag",
    ],
    "mirrored beige bag": ["no other bag"],
    "dotted silver bag": ["1 vibrant green bag"],
    "drab fuchsia bag": [
        "1 vibrant bronze bag",
        "1 striped fuchsia bag",
        "1 dotted beige bag",
    ],
    "dim beige bag": [
        "4 dotted cyan bag",
        "4 vibrant fuchsia bag",
        "5 dull violet bag",
    ],
    "shiny fuchsia bag": [
        "4 pale gold bag",
        "3 mirrored crimson bag",
        "4 plaid gold bag",
        "5 shiny yellow bag",
    ],
    "dark yellow bag": ["2 faded chartreuse bag"],
    "light chartreuse bag": [
        "1 plaid blue bag",
        "5 dim green bag",
        "1 faded chartreuse bag",
    ],
    "dull beige bag": ["2 wavy tomato bag", "1 striped yellow bag"],
    "clear tan bag": ["4 plaid yellow bag", "1 posh cyan bag", "2 dim silver bag"],
    "posh lime bag": ["3 pale brown bag", "5 dim tomato bag"],
    "dim aqua bag": [
        "4 plaid lavender bag",
        "5 striped violet bag",
        "4 plaid chartreuse bag",
    ],
    "light salmon bag": [
        "4 striped red bag",
        "2 wavy indigo bag",
        "2 light tomato bag",
        "1 dark cyan bag",
    ],
    "vibrant yellow bag": [
        "1 plaid blue bag",
        "3 dotted violet bag",
        "2 wavy red bag",
        "5 drab beige bag",
    ],
    "drab white bag": ["4 faded tan bag"],
    "light gray bag": [
        "3 plaid gold bag",
        "2 light green bag",
        "5 dim blue bag",
        "4 posh turquoise bag",
    ],
    "dull magenta bag": [
        "5 mirrored salmon bag",
        "1 mirrored chartreuse bag",
        "3 dull gray bag",
    ],
    "striped tan bag": [
        "5 plaid red bag",
        "2 dim chartreuse bag",
        "3 muted tomato bag",
    ],
    "shiny turquoise bag": [
        "1 drab gold bag",
        "5 posh teal bag",
        "2 vibrant bronze bag",
        "2 vibrant chartreuse bag",
    ],
    "bright lime bag": [
        "1 drab olive bag",
        "3 dark blue bag",
        "2 mirrored lavender bag",
        "4 shiny indigo bag",
    ],
    "mirrored lavender bag": ["no other bag"],
    "pale white bag": ["1 plaid tan bag"],
    "wavy blue bag": [
        "2 light tomato bag",
        "4 dim bronze bag",
        "1 plaid green bag",
        "2 dark maroon bag",
    ],
    "muted beige bag": [
        "1 bright black bag",
        "4 dull magenta bag",
        "2 shiny indigo bag",
    ],
    "light purple bag": ["3 bright violet bag", "2 vibrant crimson bag"],
    "mirrored cyan bag": [
        "1 wavy salmon bag",
        "2 vibrant green bag",
        "1 muted coral bag",
        "2 drab bronze bag",
    ],
    "faded coral bag": ["2 drab bronze bag", "2 wavy beige bag", "5 clear blue bag"],
    "wavy aqua bag": ["4 dotted beige bag"],
    "striped maroon bag": ["2 clear indigo bag", "4 pale black bag"],
    "dark white bag": ["1 vibrant green bag", "2 vibrant crimson bag"],
    "dim teal bag": ["1 pale plum bag"],
    "muted red bag": ["4 plaid maroon bag"],
    "plaid lavender bag": ["2 posh gold bag", "1 dark blue bag", "4 muted gold bag"],
    "drab crimson bag": [
        "2 dull green bag",
        "3 vibrant orange bag",
        "4 bright gray bag",
    ],
    "posh aqua bag": ["1 dotted fuchsia bag", "5 posh turquoise bag"],
    "muted maroon bag": [
        "4 drab green bag",
        "5 pale plum bag",
        "4 shiny indigo bag",
        "1 light chartreuse bag",
    ],
    "posh indigo bag": ["2 dim blue bag"],
    "light magenta bag": ["4 muted black bag", "1 muted green bag"],
    "dark plum bag": ["2 pale tomato bag", "2 dark maroon bag"],
    "faded lavender bag": ["2 bright magenta bag"],
    "light silver bag": ["2 pale red bag", "5 vibrant plum bag", "3 posh indigo bag"],
    "light plum bag": [
        "1 light red bag",
        "1 mirrored chartreuse bag",
        "1 dark cyan bag",
    ],
    "plaid bronze bag": [
        "4 muted turquoise bag",
        "4 mirrored blue bag",
        "4 faded yellow bag",
        "1 pale bronze bag",
    ],
    "striped cyan bag": ["4 posh black bag", "5 light maroon bag"],
    "striped magenta bag": ["5 faded brown bag", "4 pale aqua bag", "5 wavy brown bag"],
    "plaid olive bag": ["5 vibrant green bag", "2 posh plum bag"],
    "light maroon bag": ["4 muted tomato bag", "1 shiny lavender bag"],
    "mirrored salmon bag": [
        "2 dull tomato bag",
        "5 pale crimson bag",
        "2 striped yellow bag",
        "1 drab salmon bag",
    ],
    "mirrored bronze bag": ["5 posh orange bag"],
    "muted black bag": ["2 light white bag", "5 wavy black bag", "5 wavy maroon bag"],
    "drab plum bag": [
        "5 light indigo bag",
        "5 dull silver bag",
        "3 dim green bag",
        "2 dim silver bag",
    ],
    "light green bag": ["no other bag"],
    "posh salmon bag": ["3 bright lime bag"],
    "light beige bag": [
        "1 faded indigo bag",
        "4 faded teal bag",
        "1 dark green bag",
        "3 vibrant bronze bag",
    ],
    "light gold bag": ["4 pale black bag", "4 dotted white bag", "5 striped gray bag"],
    "pale lime bag": [
        "2 drab blue bag",
        "4 wavy beige bag",
        "3 striped red bag",
        "5 shiny purple bag",
    ],
    "striped crimson bag": ["5 muted white bag", "3 plaid coral bag"],
    "dull aqua bag": ["2 vibrant maroon bag", "4 posh gold bag"],
    "mirrored indigo bag": ["4 wavy white bag"],
    "clear green bag": ["2 light white bag"],
    "clear gray bag": ["3 dull coral bag", "4 dim fuchsia bag"],
    "dim coral bag": ["1 muted olive bag"],
    "dark indigo bag": [
        "5 faded chartreuse bag",
        "4 dark red bag",
        "4 shiny indigo bag",
        "3 plaid blue bag",
    ],
    "plaid purple bag": [
        "4 striped blue bag",
        "4 dark beige bag",
        "1 drab silver bag",
        "5 dotted blue bag",
    ],
    "faded tan bag": [
        "4 wavy fuchsia bag",
        "2 mirrored beige bag",
        "5 dim chartreuse bag",
    ],
    "faded white bag": [
        "1 plaid teal bag",
        "5 dark red bag",
        "4 dim olive bag",
        "2 dim bronze bag",
    ],
    "dotted chartreuse bag": ["2 muted purple bag", "4 posh gold bag"],
    "dull plum bag": ["3 dark lime bag"],
    "dull lime bag": [
        "2 bright teal bag",
        "1 vibrant aqua bag",
        "4 plaid yellow bag",
        "2 vibrant silver bag",
    ],
    "dim violet bag": ["4 wavy white bag", "3 vibrant aqua bag", "4 clear tomato bag"],
    "dotted olive bag": [
        "1 clear gray bag",
        "1 dotted fuchsia bag",
        "3 wavy tomato bag",
        "4 bright maroon bag",
    ],
    "mirrored olive bag": ["4 drab salmon bag", "4 light indigo bag"],
    "wavy brown bag": ["5 wavy beige bag"],
    "drab salmon bag": ["4 wavy maroon bag", "5 bright purple bag"],
    "bright indigo bag": ["4 mirrored tomato bag"],
    "plaid violet bag": ["3 shiny white bag", "1 posh crimson bag"],
    "drab lavender bag": ["2 vibrant gold bag", "5 faded aqua bag"],
    "clear red bag": ["3 dotted plum bag", "4 striped crimson bag"],
    "vibrant salmon bag": [
        "2 light maroon bag",
        "1 light olive bag",
        "1 mirrored tomato bag",
    ],
    "faded beige bag": ["3 plaid blue bag"],
    "vibrant magenta bag": [
        "2 vibrant black bag",
        "5 drab lavender bag",
        "4 dull indigo bag",
        "3 faded indigo bag",
    ],
    "shiny lavender bag": ["4 drab gold bag", "4 plaid violet bag"],
    "striped coral bag": ["5 vibrant green bag"],
    "dotted green bag": [
        "1 wavy maroon bag",
        "1 wavy white bag",
        "4 striped fuchsia bag",
    ],
    "dull purple bag": [
        "1 posh lavender bag",
        "5 posh brown bag",
        "1 plaid gray bag",
        "2 clear red bag",
    ],
    "mirrored teal bag": ["4 posh chartreuse bag"],
    "faded lime bag": [
        "5 dark gray bag",
        "5 light purple bag",
        "3 dotted magenta bag",
        "1 mirrored blue bag",
    ],
    "striped olive bag": [
        "3 clear purple bag",
        "2 light cyan bag",
        "5 mirrored chartreuse bag",
        "4 plaid cyan bag",
    ],
    "dark cyan bag": ["5 faded violet bag", "4 clear brown bag", "3 shiny gold bag"],
    "mirrored tan bag": ["5 dim green bag", "5 clear brown bag"],
    "wavy maroon bag": ["3 pale lime bag", "1 muted brown bag"],
    "posh brown bag": ["3 wavy salmon bag", "1 shiny tan bag", "1 plaid tomato bag"],
    "mirrored lime bag": ["5 muted tomato bag"],
    "clear teal bag": ["3 muted lavender bag", "3 dotted fuchsia bag"],
    "dim silver bag": [
        "4 drab green bag",
        "5 striped yellow bag",
        "3 vibrant maroon bag",
    ],
    "dim indigo bag": ["4 plaid blue bag", "3 bright brown bag"],
    "vibrant tomato bag": ["1 dim violet bag", "3 clear gray bag"],
    "wavy white bag": [
        "4 bright purple bag",
        "4 vibrant orange bag",
        "2 wavy yellow bag",
        "3 drab blue bag",
    ],
    "plaid beige bag": [
        "4 shiny white bag",
        "4 drab chartreuse bag",
        "1 bright orange bag",
    ],
    "pale fuchsia bag": [
        "1 plaid cyan bag",
        "3 striped coral bag",
        "5 muted violet bag",
        "3 wavy brown bag",
    ],
    "posh plum bag": ["5 dotted brown bag", "5 muted green bag"],
    "dim gold bag": ["5 mirrored lavender bag"],
    "plaid aqua bag": ["3 drab magenta bag"],
    "dotted tan bag": ["3 dull tan bag", "4 pale lime bag", "5 wavy teal bag"],
    "faded bronze bag": [
        "4 dull silver bag",
        "3 dim cyan bag",
        "5 posh chartreuse bag",
        "4 pale maroon bag",
    ],
    "wavy green bag": ["5 plaid teal bag", "2 bright teal bag"],
    "clear orange bag": [
        "5 faded yellow bag",
        "2 mirrored salmon bag",
        "3 faded coral bag",
        "4 clear tan bag",
    ],
    "wavy lavender bag": [
        "3 dotted magenta bag",
        "5 wavy tomato bag",
        "1 pale maroon bag",
        "4 dull brown bag",
    ],
    "striped chartreuse bag": ["5 dotted orange bag", "2 wavy black bag"],
    "wavy plum bag": ["2 dark tomato bag", "5 dim blue bag", "4 shiny violet bag"],
    "shiny blue bag": ["2 vibrant green bag"],
    "pale tomato bag": ["2 faded chartreuse bag"],
    "clear fuchsia bag": ["1 light lime bag", "2 shiny lavender bag"],
    "muted cyan bag": [
        "3 vibrant purple bag",
        "5 posh cyan bag",
        "4 muted red bag",
        "4 shiny indigo bag",
    ],
    "dull cyan bag": ["1 striped black bag"],
    "light turquoise bag": ["5 plaid orange bag", "2 striped yellow bag"],
    "clear lime bag": ["4 drab fuchsia bag"],
    "vibrant lavender bag": ["4 drab olive bag"],
    "plaid crimson bag": [
        "1 vibrant cyan bag",
        "5 striped gray bag",
        "2 drab gray bag",
    ],
    "shiny yellow bag": ["5 dark red bag", "1 shiny crimson bag"],
    "faded cyan bag": ["2 striped tan bag", "5 pale magenta bag"],
    "light coral bag": [
        "1 plaid gray bag",
        "3 plaid magenta bag",
        "5 faded tan bag",
        "5 clear blue bag",
    ],
    "pale blue bag": ["5 vibrant silver bag", "5 pale black bag", "4 dotted red bag"],
    "dim fuchsia bag": [
        "1 posh lime bag",
        "2 bright purple bag",
        "4 clear tan bag",
        "1 light green bag",
    ],
    "muted coral bag": ["5 dark indigo bag", "5 posh plum bag"],
    "plaid gray bag": [
        "2 dark crimson bag",
        "3 vibrant aqua bag",
        "1 posh lime bag",
        "5 faded bronze bag",
    ],
    "dotted cyan bag": [
        "4 vibrant maroon bag",
        "3 dull gray bag",
        "2 dark red bag",
        "3 pale magenta bag",
    ],
    "wavy coral bag": ["3 plaid maroon bag", "4 plaid gold bag", "1 posh lavender bag"],
    "bright crimson bag": [
        "5 faded bronze bag",
        "1 dark cyan bag",
        "4 shiny purple bag",
        "5 drab gold bag",
    ],
    "drab lime bag": ["1 dim cyan bag", "3 shiny coral bag", "3 light crimson bag"],
    "drab red bag": ["3 dim silver bag", "3 dim purple bag"],
    "dark red bag": ["5 muted gold bag"],
    "pale coral bag": ["2 posh violet bag"],
    "bright purple bag": [
        "4 mirrored lavender bag",
        "1 bright lime bag",
        "4 posh gold bag",
    ],
    "bright brown bag": [
        "3 faded aqua bag",
        "2 dull black bag",
        "4 striped magenta bag",
    ],
    "faded violet bag": [
        "5 pale maroon bag",
        "4 wavy maroon bag",
        "3 dull gray bag",
        "4 posh gold bag",
    ],
    "dark crimson bag": [
        "3 clear silver bag",
        "3 muted silver bag",
        "1 faded aqua bag",
        "5 drab gold bag",
    ],
    "dotted red bag": ["2 drab gray bag", "4 clear bronze bag"],
    "pale bronze bag": ["4 shiny salmon bag", "5 drab bronze bag", "4 dull gray bag"],
    "plaid silver bag": ["5 wavy black bag", "1 muted plum bag", "5 posh blue bag"],
    "posh green bag": ["5 shiny white bag", "5 dotted fuchsia bag", "2 pale black bag"],
    "dotted orange bag": ["5 plaid red bag"],
    "bright red bag": ["1 faded beige bag"],
    "pale brown bag": ["no other bag"],
    "drab magenta bag": [
        "4 dark indigo bag",
        "5 striped violet bag",
        "5 bright tan bag",
        "4 posh salmon bag",
    ],
    "striped indigo bag": [
        "3 dotted indigo bag",
        "3 dim lavender bag",
        "1 wavy yellow bag",
        "4 pale gold bag",
    ],
    "dark tomato bag": [
        "4 wavy yellow bag",
        "3 vibrant lavender bag",
        "1 bright black bag",
    ],
    "wavy tomato bag": ["1 wavy green bag", "2 plaid red bag", "5 wavy yellow bag"],
    "dotted aqua bag": [
        "1 drab green bag",
        "4 clear chartreuse bag",
        "5 plaid yellow bag",
    ],
    "faded black bag": ["5 clear lavender bag"],
    "muted gray bag": ["2 pale brown bag", "1 bright tan bag"],
    "bright green bag": ["1 light olive bag"],
    "wavy yellow bag": ["5 dark red bag"],
    "dark coral bag": ["4 mirrored turquoise bag", "3 dark maroon bag"],
    "shiny green bag": [
        "3 posh turquoise bag",
        "3 striped yellow bag",
        "1 bright lime bag",
        "4 dotted white bag",
    ],
    "vibrant teal bag": ["1 shiny magenta bag", "5 light maroon bag"],
    "shiny bronze bag": ["5 pale brown bag"],
    "mirrored gold bag": [
        "3 shiny crimson bag",
        "3 muted turquoise bag",
        "4 striped fuchsia bag",
        "3 vibrant lavender bag",
    ],
    "dotted salmon bag": ["2 dim lime bag", "4 pale tomato bag"],
    "dotted gold bag": [
        "1 drab magenta bag",
        "4 clear fuchsia bag",
        "3 shiny violet bag",
        "2 dark indigo bag",
    ],
    "muted olive bag": ["4 mirrored olive bag"],
    "pale green bag": ["2 plaid magenta bag", "2 bright lavender bag"],
    "clear lavender bag": ["2 vibrant gold bag", "5 clear silver bag"],
    "dark brown bag": ["4 plaid coral bag", "1 dark tan bag", "3 dotted bronze bag"],
    "dotted brown bag": ["2 wavy brown bag", "1 wavy beige bag"],
    "wavy gray bag": ["4 pale turquoise bag"],
    "pale olive bag": ["1 plaid gray bag", "1 striped coral bag"],
    "pale salmon bag": [
        "4 striped gray bag",
        "4 striped tomato bag",
        "1 bright bronze bag",
    ],
    "vibrant violet bag": ["5 bright red bag", "5 posh coral bag", "1 wavy aqua bag"],
    "shiny maroon bag": ["5 clear indigo bag", "1 striped lavender bag"],
    "vibrant red bag": [
        "5 mirrored beige bag",
        "5 wavy indigo bag",
        "2 light coral bag",
        "1 mirrored salmon bag",
    ],
    "posh yellow bag": ["5 drab gray bag", "1 dark silver bag", "3 pale maroon bag"],
    "clear white bag": ["2 drab olive bag"],
    "posh red bag": ["1 faded teal bag", "2 wavy crimson bag", "4 vibrant beige bag"],
    "striped plum bag": ["4 striped purple bag", "2 pale red bag"],
    "drab violet bag": ["1 wavy black bag"],
    "posh orange bag": ["1 pale crimson bag", "5 pale magenta bag", "3 dull olive bag"],
    "clear bronze bag": [
        "2 clear aqua bag",
        "5 mirrored plum bag",
        "2 pale crimson bag",
    ],
    "plaid white bag": ["2 faded cyan bag", "3 vibrant green bag", "5 wavy red bag"],
    "vibrant chartreuse bag": [
        "1 bright red bag",
        "2 bright gray bag",
        "5 faded bronze bag",
        "3 vibrant crimson bag",
    ],
    "dim bronze bag": ["4 dull tomato bag", "2 pale gold bag", "2 striped yellow bag"],
    "plaid yellow bag": [
        "1 pale plum bag",
        "4 bright purple bag",
        "1 bright lavender bag",
    ],
    "light orange bag": [
        "3 drab bronze bag",
        "5 wavy coral bag",
        "4 bright purple bag",
        "3 dark magenta bag",
    ],
    "faded magenta bag": [
        "4 clear tomato bag",
        "2 drab fuchsia bag",
        "1 dull gray bag",
    ],
    "mirrored magenta bag": [
        "5 vibrant maroon bag",
        "3 light fuchsia bag",
        "1 drab olive bag",
    ],
    "dark teal bag": [
        "3 shiny chartreuse bag",
        "5 mirrored fuchsia bag",
        "4 bright green bag",
    ],
    "dull teal bag": ["1 bright salmon bag", "1 mirrored salmon bag"],
    "bright silver bag": [
        "1 shiny fuchsia bag",
        "4 dotted blue bag",
        "5 posh indigo bag",
    ],
    "dull orange bag": [
        "2 striped purple bag",
        "3 muted green bag",
        "2 vibrant indigo bag",
    ],
    "dim purple bag": [
        "1 posh chartreuse bag",
        "1 dark chartreuse bag",
        "4 faded indigo bag",
        "4 bright purple bag",
    ],
    "pale cyan bag": ["1 mirrored gray bag", "2 muted beige bag", "2 plaid lime bag"],
    "vibrant gray bag": [
        "2 mirrored lavender bag",
        "1 light tomato bag",
        "3 clear indigo bag",
    ],
    "dark olive bag": [
        "1 dim fuchsia bag",
        "4 plaid teal bag",
        "1 plaid gold bag",
        "5 plaid coral bag",
    ],
    "faded green bag": [
        "3 pale olive bag",
        "1 shiny crimson bag",
        "2 faded silver bag",
    ],
    "muted plum bag": [
        "5 dotted white bag",
        "2 plaid coral bag",
        "5 dim purple bag",
        "2 dim fuchsia bag",
    ],
    "dim blue bag": ["3 pale silver bag"],
    "dark orange bag": ["3 dull crimson bag", "2 mirrored tan bag"],
    "bright blue bag": ["4 dark turquoise bag"],
    "bright black bag": [
        "3 mirrored lavender bag",
        "5 mirrored blue bag",
        "1 faded violet bag",
    ],
    "light olive bag": [
        "1 pale beige bag",
        "1 wavy maroon bag",
        "5 pale crimson bag",
        "1 striped gray bag",
    ],
    "shiny teal bag": ["2 bright white bag"],
    "posh gold bag": ["1 dark blue bag"],
    "dull crimson bag": ["2 dim bronze bag"],
    "muted gold bag": ["no other bag"],
    "striped turquoise bag": ["1 pale silver bag"],
    "posh olive bag": ["5 drab salmon bag", "2 striped coral bag"],
    "dim white bag": [
        "2 vibrant aqua bag",
        "3 bright green bag",
        "5 vibrant maroon bag",
        "4 dim tomato bag",
    ],
    "pale plum bag": ["5 bright purple bag"],
    "shiny silver bag": ["1 plaid bronze bag", "3 plaid blue bag"],
    "muted lime bag": ["1 dull lime bag"],
    "shiny plum bag": ["2 bright teal bag", "1 striped yellow bag"],
    "plaid black bag": ["1 bright purple bag"],
    "dark gold bag": ["5 faded magenta bag", "1 shiny tan bag", "1 muted crimson bag"],
    "wavy chartreuse bag": ["5 faded beige bag", "3 faded crimson bag"],
    "light cyan bag": [
        "4 drab chartreuse bag",
        "1 clear gray bag",
        "5 clear indigo bag",
        "4 vibrant black bag",
    ],
    "pale red bag": ["2 dark gray bag"],
    "clear yellow bag": ["2 drab black bag"],
    "faded silver bag": ["4 drab cyan bag", "3 light cyan bag", "5 clear tan bag"],
    "plaid turquoise bag": [
        "4 faded silver bag",
        "4 striped bronze bag",
        "1 drab purple bag",
    ],
    "pale purple bag": [
        "5 clear chartreuse bag",
        "1 plaid bronze bag",
        "5 clear cyan bag",
        "3 light tan bag",
    ],
    "bright fuchsia bag": ["4 wavy lavender bag"],
    "posh blue bag": ["5 muted gold bag", "3 dark gray bag"],
    "muted crimson bag": [
        "2 light tomato bag",
        "3 muted white bag",
        "4 muted brown bag",
        "3 faded yellow bag",
    ],
    "striped fuchsia bag": ["5 vibrant aqua bag"],
    "pale silver bag": [
        "1 vibrant orange bag",
        "5 dull gray bag",
        "3 bright teal bag",
        "1 plaid tomato bag",
    ],
    "faded blue bag": ["4 striped olive bag", "4 dull chartreuse bag"],
    "striped beige bag": ["3 drab teal bag", "1 posh gold bag"],
    "plaid maroon bag": ["5 muted turquoise bag", "2 dull aqua bag"],
    "light tan bag": [
        "1 mirrored gold bag",
        "3 shiny white bag",
        "5 faded maroon bag",
        "4 dim violet bag",
    ],
    "mirrored plum bag": [
        "4 wavy beige bag",
        "2 dark turquoise bag",
        "2 plaid teal bag",
        "5 shiny purple bag",
    ],
    "wavy teal bag": ["3 vibrant cyan bag", "3 plaid coral bag"],
    "striped bronze bag": ["3 dotted brown bag", "3 vibrant cyan bag"],
    "clear black bag": [
        "3 dim chartreuse bag",
        "2 vibrant beige bag",
        "2 clear cyan bag",
    ],
    "drab purple bag": ["2 plaid red bag", "2 vibrant aqua bag"],
    "mirrored white bag": ["2 vibrant gray bag"],
    "shiny coral bag": ["no other bag"],
    "dotted lavender bag": ["2 light brown bag"],
    "dark salmon bag": ["2 dark maroon bag", "4 dark teal bag"],
    "wavy bronze bag": ["3 striped teal bag"],
    "mirrored maroon bag": ["3 light green bag", "1 light chartreuse bag"],
    "vibrant black bag": [
        "3 clear bronze bag",
        "2 dotted beige bag",
        "2 dark crimson bag",
    ],
    "clear indigo bag": ["1 light fuchsia bag", "2 striped coral bag"],
    "mirrored black bag": ["5 plaid lime bag", "1 clear plum bag"],
    "pale chartreuse bag": ["5 plaid crimson bag"],
    "dim black bag": ["4 dotted blue bag", "2 drab indigo bag", "3 clear indigo bag"],
    "striped lime bag": ["5 light fuchsia bag", "1 dim silver bag"],
    "clear magenta bag": [
        "4 striped bronze bag",
        "3 posh orange bag",
        "4 dotted olive bag",
        "4 dull cyan bag",
    ],
    "drab chartreuse bag": [
        "4 vibrant gold bag",
        "4 vibrant orange bag",
        "3 striped red bag",
        "4 drab olive bag",
    ],
    "light yellow bag": [
        "2 dark green bag",
        "1 light fuchsia bag",
        "3 bright orange bag",
    ],
    "drab coral bag": [
        "5 light red bag",
        "4 posh plum bag",
        "4 drab crimson bag",
        "1 faded magenta bag",
    ],
    "dull brown bag": ["2 plaid cyan bag", "4 dull aqua bag", "5 posh cyan bag"],
    "dotted plum bag": ["4 dull brown bag"],
    "vibrant plum bag": [
        "1 mirrored plum bag",
        "5 vibrant olive bag",
        "5 clear gray bag",
        "3 mirrored tomato bag",
    ],
    "mirrored silver bag": [
        "2 faded indigo bag",
        "3 striped yellow bag",
        "3 muted tomato bag",
    ],
    "pale teal bag": [
        "5 mirrored white bag",
        "4 wavy plum bag",
        "4 pale indigo bag",
        "2 bright turquoise bag",
    ],
    "dotted black bag": ["3 plaid coral bag"],
    "drab gray bag": ["4 plaid red bag"],
    "striped white bag": ["2 vibrant teal bag", "3 posh aqua bag", "4 faded cyan bag"],
    "plaid green bag": ["3 mirrored chartreuse bag", "4 wavy yellow bag"],
    "posh chartreuse bag": [
        "5 clear gray bag",
        "1 striped lavender bag",
        "2 striped coral bag",
    ],
    "posh turquoise bag": ["4 bright lime bag", "2 vibrant bronze bag"],
    "muted silver bag": ["2 dull gray bag", "3 plaid tomato bag", "5 light green bag"],
    "muted salmon bag": [
        "4 dotted brown bag",
        "5 dim lavender bag",
        "3 muted violet bag",
    ],
    "dotted coral bag": ["4 drab cyan bag"],
    "striped teal bag": ["2 shiny tan bag", "3 dark turquoise bag", "3 wavy beige bag"],
    "vibrant coral bag": ["3 vibrant aqua bag", "2 pale brown bag"],
    "light indigo bag": [
        "2 dark cyan bag",
        "5 drab chartreuse bag",
        "5 clear tomato bag",
    ],
    "dim tomato bag": ["2 pale lime bag", "2 muted brown bag", "4 dull gray bag"],
    "dull gray bag": [
        "3 dotted white bag",
        "3 drab olive bag",
        "3 plaid red bag",
        "2 plaid blue bag",
    ],
    "bright beige bag": ["5 posh gold bag", "2 dull green bag", "1 wavy brown bag"],
    "dull coral bag": [
        "2 shiny gold bag",
        "2 dark red bag",
        "4 faded chartreuse bag",
        "3 vibrant orange bag",
    ],
    "dark blue bag": [
        "3 dotted white bag",
        "5 light green bag",
        "5 vibrant gold bag",
        "4 mirrored lavender bag",
    ],
    "clear turquoise bag": [
        "5 striped lavender bag",
        "5 plaid lime bag",
        "3 clear aqua bag",
        "1 mirrored salmon bag",
    ],
    "dull turquoise bag": [
        "2 vibrant fuchsia bag",
        "2 light gold bag",
        "4 striped gray bag",
    ],
    "clear aqua bag": ["1 mirrored lavender bag"],
    "drab maroon bag": [
        "1 mirrored indigo bag",
        "3 plaid crimson bag",
        "4 faded aqua bag",
        "3 clear violet bag",
    ],
    "dull black bag": ["1 shiny tan bag"],
    "muted tomato bag": ["4 light green bag"],
    "muted lavender bag": [
        "3 pale maroon bag",
        "2 shiny lavender bag",
        "1 dark beige bag",
        "1 light red bag",
    ],
    "dotted maroon bag": [
        "3 dotted magenta bag",
        "4 drab gray bag",
        "1 clear gray bag",
    ],
    "muted turquoise bag": ["5 plaid orange bag", "2 vibrant bronze bag"],
    "striped violet bag": [
        "2 plaid lavender bag",
        "4 clear tomato bag",
        "4 striped crimson bag",
    ],
    "posh purple bag": [
        "1 plaid blue bag",
        "2 pale tan bag",
        "5 light brown bag",
        "3 faded indigo bag",
    ],
    "faded chartreuse bag": [
        "5 mirrored lavender bag",
        "2 dark red bag",
        "2 dull aqua bag",
    ],
    "plaid fuchsia bag": ["4 mirrored maroon bag", "1 bright blue bag"],
    "faded teal bag": [
        "4 bright lavender bag",
        "5 light green bag",
        "2 striped yellow bag",
        "5 drab olive bag",
    ],
    "mirrored gray bag": ["2 muted green bag", "5 dim cyan bag", "2 drab yellow bag"],
    "posh bronze bag": ["1 drab blue bag"],
    "drab yellow bag": [
        "1 bright lavender bag",
        "3 vibrant aqua bag",
        "5 bright beige bag",
        "2 dull olive bag",
    ],
    "faded salmon bag": ["5 muted salmon bag"],
    "mirrored purple bag": ["2 mirrored turquoise bag", "1 pale bronze bag"],
    "shiny gray bag": ["2 dark bronze bag", "5 drab yellow bag", "2 clear salmon bag"],
    "posh gray bag": ["4 vibrant tan bag", "5 wavy maroon bag", "1 faded crimson bag"],
    "vibrant cyan bag": [
        "5 dark indigo bag",
        "3 bright purple bag",
        "1 dotted white bag",
        "3 muted gold bag",
    ],
    "dotted fuchsia bag": ["2 plaid olive bag"],
    "shiny crimson bag": [
        "4 vibrant coral bag",
        "2 light brown bag",
        "1 wavy tan bag",
        "1 clear tomato bag",
    ],
    "striped gold bag": [
        "5 vibrant olive bag",
        "4 vibrant tomato bag",
        "1 wavy red bag",
        "5 bright orange bag",
    ],
    "dotted magenta bag": [
        "5 striped yellow bag",
        "2 dull brown bag",
        "4 clear silver bag",
    ],
    "dull violet bag": ["3 posh maroon bag", "1 drab silver bag"],
    "drab gold bag": ["2 vibrant maroon bag", "5 posh plum bag", "1 shiny indigo bag"],
    "dull lavender bag": [
        "4 dull silver bag",
        "4 bright aqua bag",
        "2 striped bronze bag",
    ],
    "faded gray bag": ["1 dim white bag", "1 bright bronze bag", "4 drab violet bag"],
    "dotted lime bag": [
        "1 striped white bag",
        "4 light turquoise bag",
        "2 light maroon bag",
    ],
    "mirrored chartreuse bag": [
        "3 dull coral bag",
        "1 dark gray bag",
        "1 bright red bag",
        "4 posh blue bag",
    ],
    "drab silver bag": ["2 striped violet bag", "1 light red bag"],
    "dark beige bag": [
        "1 posh maroon bag",
        "1 dark maroon bag",
        "5 shiny tan bag",
        "3 faded chartreuse bag",
    ],
    "dim lavender bag": ["1 dim yellow bag", "3 dark coral bag", "1 wavy plum bag"],
    "shiny olive bag": ["4 pale gray bag", "5 striped coral bag", "5 dotted green bag"],
    "dim green bag": ["5 shiny purple bag", "4 mirrored lavender bag"],
    "clear tomato bag": ["1 clear aqua bag", "4 bright orange bag"],
    "striped orange bag": ["4 striped plum bag"],
    "drab green bag": ["3 shiny coral bag", "3 bright purple bag"],
    "shiny chartreuse bag": [
        "1 faded violet bag",
        "5 drab salmon bag",
        "5 vibrant orange bag",
    ],
    "shiny magenta bag": ["2 plaid crimson bag"],
    "dim magenta bag": ["1 dim fuchsia bag", "5 dark red bag", "2 shiny crimson bag"],
    "dull white bag": [
        "5 pale tan bag",
        "1 shiny teal bag",
        "5 plaid cyan bag",
        "4 pale green bag",
    ],
    "posh violet bag": [
        "4 vibrant orange bag",
        "5 mirrored fuchsia bag",
        "2 vibrant coral bag",
        "4 bright purple bag",
    ],
    "dotted crimson bag": [
        "5 vibrant gray bag",
        "2 dark red bag",
        "5 vibrant bronze bag",
    ],
    "dark black bag": ["2 pale maroon bag", "2 striped maroon bag"],
    "plaid teal bag": ["2 shiny coral bag", "1 posh gold bag"],
    "muted white bag": ["5 pale plum bag", "3 plaid teal bag"],
    "dim yellow bag": [
        "4 dark olive bag",
        "3 dim lime bag",
        "5 bright crimson bag",
        "1 dim fuchsia bag",
    ],
    "dark lime bag": ["5 posh plum bag", "4 dim tan bag", "3 bright indigo bag"],
    "muted teal bag": [
        "4 vibrant purple bag",
        "5 mirrored orange bag",
        "3 drab green bag",
    ],
    "vibrant white bag": [
        "3 pale plum bag",
        "2 bright orange bag",
        "4 posh bronze bag",
        "2 light yellow bag",
    ],
    "plaid orange bag": ["2 drab blue bag", "5 plaid lavender bag"],
    "dim olive bag": [
        "2 vibrant bronze bag",
        "5 pale violet bag",
        "1 pale magenta bag",
        "4 dim salmon bag",
    ],
    "light black bag": [
        "3 shiny purple bag",
        "4 faded tan bag",
        "5 light gold bag",
        "4 vibrant olive bag",
    ],
    "pale orange bag": [
        "5 posh maroon bag",
        "2 clear olive bag",
        "2 muted beige bag",
        "2 dim violet bag",
    ],
    "dull bronze bag": ["5 posh gold bag", "5 dark blue bag", "4 vibrant gold bag"],
    "faded aqua bag": ["4 striped fuchsia bag", "5 shiny white bag"],
    "dotted blue bag": ["1 bright salmon bag"],
    "pale maroon bag": [
        "1 light green bag",
        "3 posh gold bag",
        "2 mirrored lavender bag",
    ],
    "plaid blue bag": ["5 dull bronze bag", "4 drab blue bag"],
    "posh cyan bag": [
        "1 shiny indigo bag",
        "1 bright purple bag",
        "5 dotted white bag",
        "3 vibrant orange bag",
    ],
    "dim turquoise bag": [
        "4 clear purple bag",
        "3 mirrored cyan bag",
        "4 striped bronze bag",
    ],
    "dull fuchsia bag": ["4 light black bag"],
    "striped black bag": ["4 shiny white bag", "3 mirrored blue bag"],
    "muted tan bag": [
        "2 plaid gold bag",
        "1 vibrant lavender bag",
        "5 plaid tomato bag",
        "1 dull silver bag",
    ],
    "plaid tomato bag": [
        "1 wavy maroon bag",
        "5 muted brown bag",
        "4 faded violet bag",
    ],
    "light tomato bag": [
        "5 pale maroon bag",
        "3 shiny indigo bag",
        "1 dull bronze bag",
        "1 light green bag",
    ],
    "vibrant gold bag": ["no other bag"],
    "shiny lime bag": ["1 posh plum bag", "3 vibrant beige bag", "1 clear plum bag"],
    "drab turquoise bag": ["3 pale beige bag", "5 dull beige bag", "3 dark black bag"],
    "bright violet bag": [
        "2 plaid coral bag",
        "1 vibrant lime bag",
        "3 pale silver bag",
    ],
    "dotted white bag": ["no other bag"],
    "dark green bag": ["1 vibrant aqua bag", "3 posh cyan bag"],
    "dim cyan bag": ["4 light green bag"],
    "striped aqua bag": ["2 dotted magenta bag"],
    "posh fuchsia bag": [
        "4 dull beige bag",
        "4 light turquoise bag",
        "5 pale violet bag",
        "1 pale beige bag",
    ],
    "clear brown bag": [
        "4 wavy yellow bag",
        "1 shiny indigo bag",
        "5 wavy maroon bag",
        "1 mirrored lavender bag",
    ],
    "drab black bag": ["2 striped crimson bag"],
    "vibrant turquoise bag": ["3 dull black bag"],
    "muted purple bag": ["4 wavy cyan bag"],
    "vibrant bronze bag": ["1 drab olive bag"],
    "light red bag": ["3 vibrant cyan bag", "2 striped gray bag", "4 plaid yellow bag"],
    "pale turquoise bag": [
        "4 mirrored lavender bag",
        "2 posh maroon bag",
        "2 pale gold bag",
        "1 clear gray bag",
    ],
    "shiny aqua bag": [
        "4 clear silver bag",
        "3 vibrant lavender bag",
        "4 wavy olive bag",
    ],
    "drab teal bag": ["3 faded tan bag"],
    "mirrored turquoise bag": [
        "4 clear aqua bag",
        "3 striped crimson bag",
        "3 dull black bag",
    ],
    "vibrant beige bag": ["3 vibrant tan bag", "5 vibrant fuchsia bag"],
    "dotted bronze bag": [
        "3 muted lavender bag",
        "4 drab crimson bag",
        "1 dotted red bag",
    ],
    "muted magenta bag": [
        "2 bright teal bag",
        "4 dim olive bag",
        "3 posh brown bag",
        "1 striped gray bag",
    ],
    "striped red bag": ["no other bag"],
    "pale lavender bag": ["5 mirrored maroon bag", "3 pale gray bag"],
    "dim brown bag": ["2 dull gray bag", "4 shiny purple bag", "4 vibrant gold bag"],
    "muted yellow bag": ["2 posh teal bag", "4 vibrant cyan bag"],
    "posh tomato bag": ["4 shiny silver bag", "2 mirrored lavender bag"],
    "faded yellow bag": ["1 muted brown bag", "1 light green bag", "4 pale lime bag"],
    "vibrant orange bag": ["4 shiny coral bag", "3 drab tan bag", "1 dark blue bag"],
    "dotted beige bag": [
        "1 dim olive bag",
        "2 pale lime bag",
        "1 plaid lavender bag",
        "2 wavy brown bag",
    ],
    "pale magenta bag": [
        "2 pale brown bag",
        "2 faded violet bag",
        "1 dull gray bag",
        "2 dim green bag",
    ],
    "plaid coral bag": ["1 wavy brown bag"],
    "drab indigo bag": [
        "5 vibrant plum bag",
        "1 striped crimson bag",
        "2 dim violet bag",
    ],
    "pale crimson bag": ["2 wavy brown bag", "1 light green bag", "3 plaid orange bag"],
    "faded tomato bag": ["4 posh black bag", "1 mirrored orange bag"],
    "dim chartreuse bag": ["1 pale lime bag"],
    "bright orange bag": ["5 plaid blue bag"],
    "light crimson bag": ["3 drab gold bag"],
    "vibrant aqua bag": ["5 wavy white bag"],
    "wavy beige bag": [
        "1 mirrored beige bag",
        "3 vibrant maroon bag",
        "3 light green bag",
    ],
    "dotted gray bag": ["1 dark cyan bag", "5 mirrored fuchsia bag"],
    "dim lime bag": [
        "5 vibrant maroon bag",
        "3 striped coral bag",
        "2 plaid crimson bag",
        "5 dotted magenta bag",
    ],
    "faded purple bag": ["3 muted brown bag", "2 clear plum bag", "3 posh plum bag"],
    "dim orange bag": ["2 dotted lime bag", "3 posh violet bag", "4 dotted indigo bag"],
    "faded indigo bag": [
        "3 light brown bag",
        "3 plaid maroon bag",
        "1 bright aqua bag",
        "2 plaid red bag",
    ],
    "shiny salmon bag": [
        "1 drab bronze bag",
        "5 faded yellow bag",
        "3 vibrant gold bag",
    ],
    "light lime bag": ["1 vibrant plum bag"],
    "muted orange bag": ["5 posh red bag"],
    "vibrant fuchsia bag": [
        "5 drab gray bag",
        "4 clear chartreuse bag",
        "2 posh blue bag",
    ],
    "faded turquoise bag": [
        "2 vibrant indigo bag",
        "5 dotted indigo bag",
        "3 mirrored silver bag",
    ],
    "wavy indigo bag": ["3 vibrant white bag", "5 clear chartreuse bag"],
    "striped brown bag": ["4 dull aqua bag", "3 bright yellow bag"],
    "dotted violet bag": [
        "4 mirrored beige bag",
        "4 striped gray bag",
        "2 dim chartreuse bag",
        "3 dim brown bag",
    ],
    "dark chartreuse bag": ["5 dark turquoise bag", "4 drab gold bag"],
    "drab tomato bag": ["3 striped magenta bag", "5 shiny tomato bag"],
    "striped gray bag": ["3 shiny coral bag", "4 pale brown bag", "5 light green bag"],
    "wavy olive bag": ["5 shiny silver bag", "3 plaid blue bag", "5 shiny coral bag"],
    "mirrored tomato bag": [
        "5 clear plum bag",
        "3 bright aqua bag",
        "4 bright lime bag",
    ],
    "dark magenta bag": ["2 posh lavender bag", "5 light brown bag"],
    "shiny cyan bag": ["2 drab yellow bag", "4 dotted bronze bag"],
    "light white bag": ["3 wavy turquoise bag", "3 vibrant beige bag"],
    "shiny indigo bag": [
        "4 pale brown bag",
        "1 drab olive bag",
        "2 dark red bag",
        "1 striped gray bag",
    ],
    "wavy lime bag": ["3 dark cyan bag", "1 vibrant green bag"],
    "vibrant brown bag": ["4 light bronze bag", "1 drab black bag"],
    "drab tan bag": ["1 striped gray bag"],
    "dotted yellow bag": ["5 dotted coral bag", "4 striped magenta bag"],
    "shiny brown bag": ["3 dull beige bag", "2 striped silver bag"],
    "dull chartreuse bag": ["3 pale black bag"],
    "pale aqua bag": [
        "1 posh turquoise bag",
        "3 vibrant aqua bag",
        "4 shiny white bag",
    ],
    "muted indigo bag": [
        "4 dotted aqua bag",
        "3 striped black bag",
        "3 pale lime bag",
        "3 dotted violet bag",
    ],
    "mirrored yellow bag": ["1 dim chartreuse bag", "3 pale black bag"],
    "posh beige bag": ["1 plaid bronze bag", "5 vibrant tan bag", "3 posh tomato bag"],
    "dim plum bag": ["3 plaid gold bag", "4 dim chartreuse bag", "1 pale green bag"],
    "wavy violet bag": [
        "5 striped turquoise bag",
        "4 drab chartreuse bag",
        "4 plaid maroon bag",
    ],
    "dim crimson bag": ["1 posh chartreuse bag"],
    "dull salmon bag": ["3 muted black bag"],
    "vibrant blue bag": ["4 dark white bag", "5 mirrored plum bag"],
    "bright gray bag": ["4 bright lavender bag"],
    "bright plum bag": [
        "4 bright tomato bag",
        "3 light gold bag",
        "2 bright aqua bag",
        "4 striped red bag",
    ],
    "clear chartreuse bag": ["1 plaid yellow bag"],
    "shiny tan bag": ["4 pale maroon bag"],
    "mirrored brown bag": [
        "2 pale maroon bag",
        "3 dark beige bag",
        "1 mirrored lime bag",
        "4 bright purple bag",
    ],
    "plaid plum bag": [
        "5 pale magenta bag",
        "2 mirrored lavender bag",
        "2 plaid gold bag",
    ],
    "faded crimson bag": [
        "4 plaid maroon bag",
        "1 light turquoise bag",
        "5 posh purple bag",
        "1 wavy beige bag",
    ],
    "clear blue bag": ["3 dim salmon bag", "2 wavy fuchsia bag", "3 vibrant olive bag"],
    "light aqua bag": ["4 posh aqua bag", "4 striped black bag"],
    "bright chartreuse bag": ["2 plaid olive bag", "4 striped lavender bag"],
    "plaid tan bag": ["1 vibrant aqua bag"],
    "faded red bag": ["1 plaid maroon bag", "2 muted coral bag", "4 light brown bag"],
    "clear gold bag": [
        "4 striped red bag",
        "3 shiny gold bag",
        "4 light green bag",
        "4 dark blue bag",
    ],
    "light teal bag": ["5 muted tomato bag", "3 dim cyan bag"],
    "pale gold bag": ["4 dim fuchsia bag", "4 dark indigo bag"],
    "faded maroon bag": [
        "5 dim silver bag",
        "4 vibrant cyan bag",
        "3 plaid coral bag",
        "3 bright purple bag",
    ],
    "plaid red bag": ["2 dull bronze bag", "5 bright lime bag"],
    "mirrored blue bag": [
        "2 plaid coral bag",
        "5 dull indigo bag",
        "4 drab chartreuse bag",
        "3 vibrant gold bag",
    ],
    "faded orange bag": ["2 wavy green bag", "5 bright purple bag", "1 dark cyan bag"],
    "mirrored fuchsia bag": ["5 light green bag"],
    "dark turquoise bag": ["4 bright white bag"],
    "shiny violet bag": ["1 pale magenta bag"],
    "shiny tomato bag": ["2 pale violet bag", "4 pale brown bag"],
    "posh magenta bag": ["2 shiny tan bag", "2 vibrant tan bag"],
    "plaid magenta bag": [
        "1 drab chartreuse bag",
        "1 vibrant orange bag",
        "2 plaid red bag",
        "2 faded yellow bag",
    ],
    "light blue bag": ["5 dotted bronze bag", "3 dotted brown bag"],
    "plaid indigo bag": ["3 bright orange bag"],
    "striped tomato bag": ["2 striped yellow bag"],
    "shiny purple bag": ["5 dull bronze bag", "3 dull aqua bag"],
    "posh white bag": ["1 plaid teal bag", "1 striped blue bag", "3 posh magenta bag"],
    "clear violet bag": ["1 drab bronze bag"],
    "muted blue bag": ["3 dotted bronze bag", "2 light olive bag"],
    "muted chartreuse bag": [
        "4 posh purple bag",
        "1 dull magenta bag",
        "1 dim silver bag",
        "5 bright indigo bag",
    ],
    "dark purple bag": [
        "3 faded aqua bag",
        "2 dull beige bag",
        "4 plaid coral bag",
        "1 pale black bag",
    ],
    "wavy silver bag": [
        "5 muted salmon bag",
        "2 bright salmon bag",
        "1 posh magenta bag",
        "2 dim brown bag",
    ],
    "posh black bag": ["1 dim tomato bag"],
    "bright lavender bag": [
        "1 vibrant crimson bag",
        "3 posh turquoise bag",
        "5 faded yellow bag",
    ],
    "dull green bag": [
        "3 faded chartreuse bag",
        "2 faded beige bag",
        "2 shiny coral bag",
    ],
    "posh crimson bag": [
        "5 bright red bag",
        "3 clear brown bag",
        "4 shiny salmon bag",
        "3 vibrant orange bag",
    ],
    "plaid gold bag": [
        "2 plaid tomato bag",
        "4 muted turquoise bag",
        "4 clear salmon bag",
    ],
    "bright coral bag": [
        "5 mirrored lavender bag",
        "1 bright yellow bag",
        "4 clear black bag",
        "5 posh lavender bag",
    ],
    "wavy black bag": ["3 dim salmon bag"],
    "clear silver bag": ["4 plaid magenta bag"],
    "striped lavender bag": [
        "3 muted gold bag",
        "4 light brown bag",
        "2 vibrant green bag",
    ],
    "dull blue bag": ["2 plaid violet bag", "5 vibrant white bag"],
    "dull olive bag": [
        "2 clear chartreuse bag",
        "1 pale violet bag",
        "2 vibrant crimson bag",
    ],
    "wavy tan bag": ["4 posh cyan bag", "5 clear silver bag"],
    "bright salmon bag": ["1 drab tan bag", "1 dull indigo bag"],
    "wavy turquoise bag": ["1 dark maroon bag"],
    "drab olive bag": [
        "2 muted gold bag",
        "5 dark blue bag",
        "4 mirrored lavender bag",
    ],
    "drab cyan bag": ["1 drab blue bag", "1 vibrant bronze bag"],
    "pale beige bag": [
        "5 clear gold bag",
        "3 dim tomato bag",
        "5 posh crimson bag",
        "2 drab gray bag",
    ],
    "bright teal bag": ["1 wavy maroon bag", "4 dim green bag", "2 shiny tan bag"],
    "drab aqua bag": ["3 clear cyan bag", "3 dull silver bag"],
    "shiny white bag": [
        "4 dim green bag",
        "5 faded violet bag",
        "5 posh cyan bag",
        "4 pale brown bag",
    ],
    "bright magenta bag": ["1 bright indigo bag"],
    "bright yellow bag": ["1 dark red bag", "2 posh cyan bag"],
    "dotted tomato bag": [
        "4 drab salmon bag",
        "1 shiny coral bag",
        "1 faded beige bag",
        "2 shiny magenta bag",
    ],
    "vibrant silver bag": ["5 clear orange bag"],
    "dark aqua bag": [
        "3 bright tan bag",
        "3 dim cyan bag",
        "1 plaid chartreuse bag",
        "1 clear orange bag",
    ],
    "shiny red bag": ["4 clear tomato bag"],
    "plaid lime bag": ["3 mirrored lavender bag", "4 drab green bag"],
    "shiny gold bag": [
        "4 striped yellow bag",
        "3 drab olive bag",
        "1 bright purple bag",
    ],
    "bright maroon bag": [
        "5 dull indigo bag",
        "1 mirrored lavender bag",
        "5 posh salmon bag",
    ],
    "light bronze bag": ["3 dim tan bag", "4 dotted brown bag", "1 drab green bag"],
    "light fuchsia bag": ["3 shiny crimson bag", "2 bright salmon bag"],
    "faded plum bag": ["3 dull brown bag"],
    "posh silver bag": [
        "3 wavy bronze bag",
        "2 plaid green bag",
        "5 drab fuchsia bag",
        "1 wavy red bag",
    ],
    "bright tomato bag": ["2 bright black bag", "2 clear brown bag"],
    "dull gold bag": ["1 dark salmon bag"],
    "clear plum bag": ["1 mirrored tan bag", "1 shiny coral bag", "2 clear tan bag"],
    "pale tan bag": ["1 bright red bag", "5 light yellow bag", "4 vibrant olive bag"],
    "plaid salmon bag": ["3 drab maroon bag", "1 posh black bag", "1 vibrant blue bag"],
    "striped silver bag": [
        "4 faded coral bag",
        "5 clear black bag",
        "4 dark chartreuse bag",
        "5 pale tan bag",
    ],
    "faded brown bag": ["5 wavy black bag"],
    "faded gold bag": [
        "5 plaid maroon bag",
        "4 posh blue bag",
        "4 posh crimson bag",
        "1 bright teal bag",
    ],
    "dull tomato bag": ["4 muted coral bag", "5 drab tan bag"],
    "dotted turquoise bag": ["5 light gray bag", "4 plaid cyan bag", "5 dark lime bag"],
    "dull indigo bag": ["4 plaid red bag", "5 bright aqua bag"],
    "dull yellow bag": ["4 muted crimson bag", "5 bright black bag"],
    "striped yellow bag": [
        "4 dark red bag",
        "3 vibrant crimson bag",
        "4 vibrant maroon bag",
        "1 mirrored lavender bag",
    ],
    "dotted indigo bag": ["4 drab turquoise bag", "2 posh purple bag"],
    "mirrored aqua bag": [
        "4 plaid blue bag",
        "1 dark white bag",
        "4 bright magenta bag",
        "5 drab lime bag",
    ],
    "striped blue bag": [
        "5 dotted red bag",
        "3 light fuchsia bag",
        "3 light crimson bag",
        "5 striped yellow bag",
    ],
    "shiny orange bag": ["1 shiny crimson bag", "4 vibrant silver bag"],
    "dim maroon bag": ["2 bright lavender bag"],
    "wavy gold bag": ["2 muted chartreuse bag"],
    "bright bronze bag": ["1 posh crimson bag", "4 wavy red bag"],
    "dark fuchsia bag": [
        "2 pale tan bag",
        "3 posh orange bag",
        "1 shiny chartreuse bag",
    ],
    "pale violet bag": ["1 drab green bag", "1 drab tan bag"],
    "bright turquoise bag": ["2 posh gold bag", "3 dull green bag", "2 pale tan bag"],
    "wavy salmon bag": ["5 plaid olive bag", "5 posh cyan bag"],
    "wavy magenta bag": ["5 plaid chartreuse bag", "5 muted bronze bag"],
    "dark violet bag": ["3 dim chartreuse bag", "1 faded aqua bag"],
    "dull silver bag": ["5 plaid orange bag"],
    "vibrant purple bag": ["2 mirrored turquoise bag", "5 plaid gray bag"],
    "dark lavender bag": ["4 dull red bag"],
    "dark silver bag": [
        "1 posh brown bag",
        "4 wavy white bag",
        "5 muted fuchsia bag",
        "1 clear plum bag",
    ],
    "dark gray bag": [
        "4 wavy white bag",
        "5 plaid lavender bag",
        "2 dull aqua bag",
        "4 bright purple bag",
    ],
    "pale indigo bag": ["5 plaid green bag", "2 dull aqua bag"],
    "posh maroon bag": ["4 plaid magenta bag", "4 bright orange bag"],
    "muted violet bag": ["4 muted brown bag"],
    "mirrored violet bag": ["3 dim tomato bag"],
    "posh lavender bag": ["3 muted turquoise bag", "4 wavy maroon bag"],
    "posh tan bag": [
        "4 muted coral bag",
        "4 shiny beige bag",
        "5 light red bag",
        "4 faded beige bag",
    ],
    "vibrant crimson bag": [
        "4 mirrored lavender bag",
        "2 mirrored beige bag",
        "1 striped red bag",
    ],
    "bright white bag": [
        "3 striped fuchsia bag",
        "2 mirrored tan bag",
        "4 dull bronze bag",
        "4 posh plum bag",
    ],
    "bright cyan bag": [
        "5 light cyan bag",
        "3 vibrant crimson bag",
        "1 faded cyan bag",
    ],
    "clear beige bag": [
        "1 plaid yellow bag",
        "5 drab white bag",
        "2 drab lime bag",
        "5 dim orange bag",
    ],
    "mirrored coral bag": [
        "2 light tomato bag",
        "3 wavy bronze bag",
        "3 mirrored fuchsia bag",
    ],
    "vibrant olive bag": [
        "2 posh turquoise bag",
        "3 mirrored fuchsia bag",
        "4 dotted beige bag",
    ],
    "shiny black bag": [
        "2 faded coral bag",
        "4 plaid indigo bag",
        "3 dark violet bag",
        "4 posh indigo bag",
    ],
    "mirrored green bag": ["4 bright teal bag"],
    "clear purple bag": [
        "1 posh turquoise bag",
        "3 dull black bag",
        "3 faded violet bag",
    ],
    "vibrant tan bag": ["4 drab blue bag"],
    "mirrored crimson bag": [
        "2 mirrored chartreuse bag",
        "4 muted red bag",
        "4 vibrant purple bag",
    ],
    "posh teal bag": [
        "4 dim fuchsia bag",
        "2 shiny tan bag",
        "2 dull indigo bag",
        "3 pale plum bag",
    ],
    "striped salmon bag": ["3 plaid fuchsia bag", "3 muted teal bag"],
    "wavy fuchsia bag": [
        "1 drab green bag",
        "2 dim salmon bag",
        "2 light crimson bag",
        "4 muted turquoise bag",
    ],
    "clear cyan bag": ["4 mirrored cyan bag", "1 dull bronze bag", "4 dim brown bag"],
    "posh coral bag": ["3 pale beige bag", "2 plaid salmon bag"],
    "shiny beige bag": ["5 faded violet bag"],
    "wavy cyan bag": ["2 posh lime bag", "2 dotted white bag", "4 dim lime bag"],
    "dark tan bag": [
        "5 clear green bag",
        "1 light cyan bag",
        "5 light chartreuse bag",
        "1 dark lime bag",
    ],
    "clear coral bag": [
        "2 wavy beige bag",
        "2 muted cyan bag",
        "5 dark turquoise bag",
        "4 posh green bag",
    ],
    "drab orange bag": ["5 wavy salmon bag", "5 wavy olive bag", "3 posh green bag"],
    "vibrant maroon bag": ["no other bag"],
    "drab beige bag": ["1 dark red bag"],
    "muted bronze bag": [
        "4 striped teal bag",
        "5 faded brown bag",
        "4 light silver bag",
        "3 muted beige bag",
    ],
    "muted fuchsia bag": [
        "2 shiny coral bag",
        "4 dull tomato bag",
        "1 wavy teal bag",
        "5 faded tan bag",
    ],
    "plaid brown bag": ["5 dull magenta bag"],
    "dim salmon bag": [
        "3 mirrored lavender bag",
        "2 shiny salmon bag",
        "4 plaid lavender bag",
    ],
    "wavy purple bag": ["1 shiny yellow bag", "1 dim plum bag"],
    "bright aqua bag": ["4 plaid red bag", "5 pale lime bag", "5 bright lime bag"],
    "vibrant lime bag": ["5 light green bag"],
    "dark maroon bag": ["5 drab bronze bag", "4 bright red bag", "1 posh cyan bag"],
    "wavy red bag": [
        "2 mirrored beige bag",
        "5 muted crimson bag",
        "5 vibrant orange bag",
        "3 posh turquoise bag",
    ],
    "drab brown bag": ["1 faded tan bag", "3 vibrant maroon bag"],
}
